
UPSMON_DOPATROLSRCH = compile preProcessFileLineNumbers "FMFG\SargeAI\scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_DOPATROLSRCH.sqf";
UPSMON_SrchPtrlFlankPos = compile preProcessFileLineNumbers "FMFG\SargeAI\scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_SrchPtrlFlankPos.sqf";
UPSMON_GETINPATROLSRCH = compile preProcessFileLineNumbers "FMFG\SargeAI\scripts\UPSMON\MODULES\ORDERS\UPSMON_PATROLSRCH\fnc\UPSMON_GETINPATROLSRCH.sqf";
